input_data_path: 'data/heart_cleveland_upload.csv'
output_model_path: 'models/rf_model.pkl'
metric_path: 'models/rf_model_test_metrics.json'

splitting_params:
  val_size: 0.2 
  random_state: 54 

model_params:
  model_type: 'RandomForest' 
  random_state: 54

feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  features_to_drop: []
  target_col: 'condition'
  transformer_type: ''


