input_data_path: 'data/test_data/test.csv'
output_data_path: 'predicts/log_reg_predictions.csv'
data_for_transform: 'data/heart_cleveland_upload.csv'
model_path: 'models/log_reg_model.pkl'

feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  features_to_drop: []
  target_col: 'condition'
  transformer_type: 'default'


