input_data_path: 'data/heart_cleveland_upload.csv'
output_data_path: 'predicts/rf_predictions.csv'
model_path: 'models/rf_model.pkl'

feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  features_to_drop: []
  transformer_type: ''


